* Big Data for Financial Technology - Course Proposal
** Background
The purpose of this proposal is to expose a portfolio of work that I have been
contemplating and working on since Fall of 2015, and to request a partnership
with the Big Data program at SFU to receive resources to continue
this work in the form of research, curriculum production, or some other way. The
theme of this portfolio can be summarized as Big Data for Financial Technology.
The inspiration for studying this field comes from a fascination, and passion
for two independent frontiers of technology: Biologically inspired probabilistic
modelling (AI), and Cryptocurrency Ecosystems. I believe that I have found an
incredibly fascinating niche in the intersection of these two emerging
industrial fields. 

In 2015, I was already obsessed with Bitcoin. I saw it as a liberating
technology with the potential to lubricate global economies, drive financial and
technological innovation, and put an end to post-colonial financial control systems.
I also believed in at as a source of wealth, an intrinsically deflationary currency, a currency that will always be worth more tomorrow than today.
In other words, I saw Bitcoin as a system that rewards people for consuming less, a solution to the capitalistic, materialistic,
consumerism which is driving humans and the planet to destruction. As a young man, who had never
experienced financial wealth, it offered a vehicle for monetary ascension if leveraged properly. Seeing the
extreme volatility in the price of Bitcoin, I began to understand the magnitude to which one could multiply an investment
if they could somehow predict future price movements of Bitcoin.

Fall 2015 I enrolled in a graduate course on Machine Learning with Russ Greiner at University of Alberta. The first lecture was dedicated
to the motivation for machine learning, a preview of the powerful problems that can be solved with probabilistic modelling rather than explicit programming.
It instantly clicked in my head that machine learning could be used to model the price movement of Bitcoin. I have dedicated my life since then to accomplishing
just that.

Since that time, I have continued relentlessly studying AI and Cryptocurrencies. I took a course on Reinforcement Learning with Richard Sutton, AI in games, 
Probabilistic Graphical Models, as well as online courses: Machine Learning with Andrew NG, Deep Learning with Tensorflow, and Bitcoin and Cryptocurrecy Technology.

After graduating my undergrad, I spent the subsequent four months attempting to manifest my vision. I was implementing rudimentary trading algorithms, collecting
social media data from twitter, and reddit, attempting to collect price history data, aggregate this data, and apply a machine learning model which could execute
automated trades. I realized two things from this experience: Firstly, I was lacking depth of knowledge in some relevant areas, secondly, and most critically,
I would not be able to pull of a successful execution of my vision while working in solitude. I needed people to discuss ideas with, and assist in engineering tasks.
It was at this time that I decided to pursue a masters degree which could provide me with the necessary knowledge, skill, and network, that is necessary to execute
my vision. This is when I discovered the SFU Big Data program.

The Big Data program has equipped me far beyond anything I could have imagined. The tools and technology that I have been studying have been exactly what I need
for my project. I have been exposed to a startup environment(Matt Saba), I have met brilliant hackers(Jacky), I have met domain experts coming from FinTech(Jacky, Steven, Arul),
and enthusiastic individuals(Vincent, Paula).

*** Financial Technology and Big Data
*** RBC and Industrial Partners
Number of Coops with Banks
Brain Drain!
The Big Data Empire
** Proposal
Two RA Terms
I propose two semesters of Research Assistant positions, Summer 2018 and Fall 2018. The goals of the respective semesters are the following:
*** Summer 2018
**** Reconaissance at RBC
A key concept that Dr. Hefeeda has highlighted is that any addition to the Big Data Curriculum should be aligned with industrial demands. Banking and Finance
is a huge industrial sector with a large demand for Data Scientists and Big Data solutions. Big Data has a huge intersection with Financial Technology, or
FinTech. However, much of the Big Data concepts which are fundamental to FinTech are not currently within the scope of the Big Data program. Some examples that
I am aware of include: Time Series Analysis, Signal Processing, Data Streaming, Asset and Risk Management, Cryptocurrency Systems, Blockchain and Smart Contracts,
AI for Asset and Risk Management.

The above concepts stem more from my own passions than from industrial alignment. Thus my time at RBC will serve as a needs assessment for FinTech in industry,
from a Big Data perspective. During my time at RBC I will generate a needs assessment report for industrial FinTech from a Big Data perspective. I will do this
via personal observation, as well as explicit interviews with RBC Technology and Operations employees. 

I will produce a report, as well as a presentation for the Big Data department when I return to Burnaby in September 2018.

**** Quantopia Research
During my four month COOP with RBC, in addition to investigating industrial needs for Big Data in FinTech, I propose an additional research component to my
RA position. I would like to progress through the lectures [[https://www.quantopian.com/lectures][here]]. These lectures illustrate quantitative finance through the lens of Data Science. From this
resource I will curate the relevant and non-redundant lessons into a unit to be incorporated into the Big Data Curriculum. 

For this part of the RA position, I will compile a repository of Jupyter Notebook lectures.
*** Fall 2018
Algorithms
Course Development / Course Offering / Seminar Style?
Work with a professor - Steven?
** Course Content
**** Big Data in Banking, Assets, and Economics
     Assets and the Economy as Big Data
     Risk Management
     Arbitrage 
**** Time Series, Signal Processing, Streaming and Dynamic Data
***** Time Series
     This area is, I believe, the most significant gap in the content covered by 
Programming for Big Data I and II. The only case in which time series data is mentioned
is in the context of Natural Language Processing. I believe Time Series analysis deserves
a dedicated study in it's own right. Time Series analysis is critical when working with
datasets such as Audio, Price Movement, EEG signals, Sensor Data, Web analysis, and security.

***** Signal Processing
      Fourier Transform is a fundamental concept for Data manipulation which is not
covered in the Big Data program. It is relevant in Image processing, audio processing,
signal processing of any kind in which you wish to move from the time domain to 
the frequency domain.

***** Streaming Data
      Working with streaming data is a very hot topic in Big Data today. Financial applications often necessetate work with
streaming data. FinTech could serve as the perfect sandbox for Big Data students to practice working with data streaming. For
example, [[https://spark.apache.org/streaming/][Spark Streaming]] is a very new tool that students should become familiar with.
**** Cryptocurrency Ecosystems
     Blockchain and Cryptocurrency
     Ethereum and Smart Contracts
     Economic Nature of Cryptocurrency Systems
     Visualization and Exploratory Analysis
     Opportunity: Business, Arbitrage, and Investment
**** Artificial Intelligence and Portfolio Management
     Portfolio Management
     Algorithmic Trading
     Deep Learning, Reinforcement Learning, and Evolution Strategies
     
** Credentials
*** My Portfolio
**** My work on Arbitrage and Visualization
Arbitrage Paper - https://shawnwanderson.github.io/pdf/constructing-scalable-system.pdf
Arbitrage Video -  https://photos.app.goo.gl/OCN4epsVFTWRdiX32
CryptViz Proposal - https://github.com/LinuxIsCool/733Project
**** My work on Automated Trading
Slide Deck
Summary
756 Proposal
Original Paper
**** My work on Signal Processing and Time Series
Field Recordings
EEG
*** My Resume
*** My GitHub
*** My Website
*** GPA
Fall - 12 Credits - Big Data Lab, Machine Learning, Data Mining - GPA: 3.83
*** Reference
Steven Bergner
Diana Cuckieman
Jiannan Wang
Ryan Shae
Greg Baker
Maxwell Librecht
Paula Scott
** Resources
**** Course Content
Arul Bharathi on Big Data for Banking: https://www.slideshare.net/arulbharathi/data-science-use-cases-in-banking
Princeton – Blockchain and Cryptocurrency Technology  https://www.coursera.org/learn/cryptocurrency
Quantopia https://www.quantopian.com/lectures
**** Interest in FinTech
Industry - RBC, Scotia, ect.
Block Foundation
Steven Bergner
AI seminar feedback
Arbitrage Presentation
Jacky Lok, Vincent Chu, Brieh
Fireout - Matt Saba, 
